---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.278
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.32.0
  hooks:
  - id: yamllint
    exclude: '^tests/tool/testdata/.*\.yaml$'
    args:
    - -c
    - ".yaml-lint.yaml"
